# Codemagic configuration for iOS build with manual signing via UI
workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: CodeMagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.zupy.scanner"
      vars:
        APP_STORE_APPLE_ID: "6746722127"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_VERSION: "1.1.0"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependências npm do projeto Capacitor
        script: |
          npm install

      - name: Instalar dependências Cocoapods
        script: |
          cd ios/App
          pod install
          cd ../../

      - name: Verificar se App.xcworkspace existe
        script: |
          ls -la ios/App/*.xcworkspace

      - name: Compilar código web para a pasta 'build'
        script: npm run build

      - name: Atualizar dependências nativas e copiar assets web
        script: |
          npx cap sync

      - name: Definir versão do app (CFBundleShortVersionString)
        script: |
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $APP_VERSION" ios/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/App/Info.plist

      - name: Configurar assinatura com certificados conectados
        script: |
          xcode-project use-profiles

      - name: Incrementar build number (CFBundleVersion)
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          NEXT_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))

          echo "Último build: $LATEST_BUILD_NUMBER"
          echo "Novo build: $NEXT_BUILD_NUMBER"

          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEXT_BUILD_NUMBER" ios/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEXT_BUILD_NUMBER" ios/App/Info.plist

      - name: Build IPA assinado para distribuição
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - webmaster@zupy.com.br
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
