# Codemagic configuration for React (Node.js) project
workflows:
  react-app:
    name: React Build and Test
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test -- --watchAll=false || true
      - name: Build app
        script: |
          npm run build
    artifacts:
      - build/**
    publishing:
      email:
        recipients:
          - webmaster@zupy.com.br
        notify_on_build_status: true
