name: Build iOS App for Zupy Scanner

on:
  workflow_dispatch:  # Executa manualmente pelo GitHub

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Sync Capacitor with iOS
        run: |
          npm install -g @capacitor/cli
          npx cap sync ios

      - name: Validate Xcode project
        run: |
          if [ ! -f ios/App/App.xcodeproj/project.pbxproj ]; then
            echo "❌ Erro: projeto Xcode não encontrado em ios/App/"
            exit 1
          else
            echo "✅ Projeto Xcode encontrado!"
          fi

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod install

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Build iOS archive
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/ZupyScanner.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/ZupyScanner.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ios/exportOptions.plist

      - name: List contents of build folder
        run: |
          echo "Arquivos encontrados na pasta build:"
          ls -la build/

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zupy-scanner-ipa
          path: build/**/*.ipa
